### ISSUE TITLE
handle non cacheable responses (in cache)

### ISSUE THREAD

**Issue by pavlikovskiy** [frontcache/frontcache#10]
now - raised exception and second request (forward) is performed
should be - reuse response (do not make second request)

org.frontcache.core.FrontCacheException: Not cacheable content type (image/x-icon) for http://localhost:8080/favicon.ico
	at org.frontcache.core.FCUtils.httpResponse2WebComponent(FCUtils.java:88)
	at org.frontcache.core.FCUtils.dynamicCall(FCUtils.java:62)
	at org.frontcache.cache.CacheProcessorBase.processRequest(CacheProcessorBase.java:31)
	at org.frontcache.FrontCacheEngine.processRequest(FrontCacheEngine.java:200)
	at org.frontcache.FrontCacheServlet.service(FrontCacheServlet.java:55)

2016-01-13_20:25:10.774 0 1 4973 -1 http://localhost:8080/favicon.ico

**Comment by pavlikovskiy** [comment]
done

**Comment by pavlikovskiy** [comment]
also can be handled with ignore-cache-uri filters
